// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umcbjukdgbbrawlljxye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtY2JqdWtkZ2JicmF3bGxqeHllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4OTI1ODgsImV4cCI6MjA1NTQ2ODU4OH0.V01KrIHAl0Wz8cIPncuZA8SykzwZ3cGB9OK9iXEQTzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);